# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16c2ae9fe50b07633c470d3a1b9615bed11473c2e0e4c5353891254acacfa6ffa1d603f99757208f01d0d411c45fcefe08bdbad9d830bec8fd9b81694366d917

test:
  secret_key_base: f81978b32ad513aac42483434e3756fa64a7be756aa5c218f34bad36410c244d2ae6fb9bbd9ca6ec33400af2857325a827a7a8511dd8f9ec6e3aa594da016283

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
